In [ ]:
import re, nltk, pandas as pd, numpy as np
from gensim.parsing.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from gensim.parsing.preprocessing import remove_stopwords

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
downloaded = drive.CreateFile({'id':'12CUjW29tTTxYAcPhxuKb_qSn0UTzc4BR'}) # replace the id with id of file you want to access
downloaded.GetContentFile('imdb_sentiment.csv') 

In [ ]:
data = pd.read_csv('imdb_sentiment.csv')
data.head()

review  sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [ ]:
data.head()

review  sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

## Text Cleaning

In [ ]:
stemmer = PorterStemmer()
docs_clean = data['review'].str.lower()
docs_clean = docs_clean.str.replace('-',' ').str.replace('[^\w+\s]', '')
docs_clean = docs_clean.apply(lambda x : remove_stopwords(x)) # stopword removal
docs_clean = stemmer.stem_documents(docs_clean) # stem documents
docs_clean[:5]


['slow move aimless movi distress drift young man',
 'sure lost flat charact audienc nearli half walk',
 'attempt arti black white clever camera angl movi disappoint ridicul act poor plot line non exist',
 'littl music speak',
 'best scene movi gerardo try song keep run head']

In [ ]:
vectorizer = CountVectorizer().fit(docs_clean) #initiating the fn and fitting the cleaned doc

In [ ]:
vocab = vectorizer.get_feature_names() #this fn will be able to identify individual tokens in the doc & extract token names 

In [ ]:
print(vocab[:10])
print('length is :',len(vocab))

['010', '10', '1010', '110', '12', '13', '15', '17', '18th', '1928']
length is : 2373


In [ ]:
vocab

['act',
 'actor',
 'actual',
 'art',
 'bad',
 'beauti',
 'believ',
 'best',
 'better',
 'big',
 'bore',
 'camera',
 'cast',
 'charact',
 'come',
 'dialogu',
 'didnt',
 'direct',
 'disappoint',
 'doesnt',
 'dont',
 'effect',
 'end',
 'enjoi',
 'excel',
 'feel',
 'film',
 'funni',
 'good',
 'great',
 'job',
 'know',
 'life',
 'like',
 'line',
 'littl',
 'look',
 'lot',
 'love',
 'make',
 'man',
 'minut',
 'movi',
 'music',
 'peopl',
 'perform',
 'piec',
 'plai',
 'plot',
 'predict',
 'pretti',
 'rate',
 'real',
 'recommend',
 'right',
 'saw',
 'scene',
 'script',
 'seen',
 'set',
 'short',
 'stori',
 'stupid',
 'terribl',
 'thing',
 'think',
 'thought',
 'time',
 'total',
 'understand',
 'wai',
 'want',
 'wast',
 'watch',
 'wonder',
 'work',
 'wors',
 'worst',
 'worth',
 'write',
 'year']

In [ ]:
# Another way of doing operations 
vectorizer2 = CountVectorizer(token_pattern='[a-z]+').fit(docs_clean) #token_pattern = '[a-z]+' specifying all word tokens 
vocab = vectorizer2.get_feature_names()
print(vocab[:10])
print('length is :',len(vocab))

['a', 'aailiyah', 'abandon', 'abil', 'abroad', 'absolut', 'abstrus', 'abysm', 'academi', 'accent']
length is : 2345


In [ ]:
vectorizer3 = CountVectorizer(token_pattern='[a-z]{3,10}').fit(docs_clean) #token_pattern='[a-z]{3,10}: specifying size of token as min & max no of chars in words
vocab = vectorizer3.get_feature_names()
print(vocab[:10])
print('length is :',len(vocab))

['aailiyah', 'abandon', 'abil', 'abroad', 'absolut', 'abstrus', 'abysm', 'academi', 'accent', 'access']
length is : 2304


In [ ]:
vectorizer4 = CountVectorizer(token_pattern='[a-z]{3,10}', min_df=5).fit(docs_clean) # min_df is used to reduce those tokens which rally up in few docs; used for discarding tokens
vocab = vectorizer4.get_feature_names()
print(vocab[:10])
print('length is :',len(vocab))

['absolut', 'act', 'action', 'actor', 'actress', 'actual', 'amaz', 'annoi', 'aphi', 'art']
length is : 255


* length reduced drastically from being 2304 to 255

In [ ]:
vectorizer5 = CountVectorizer(token_pattern='[a-z]{3,10}', min_df=10).fit(docs_clean) # min_df is used to reduce those tokens which rally up in few docs; used for discarding tokens
vocab = vectorizer5.get_feature_names()
print(vocab[:10])
print('length is :',len(vocab))

['act', 'actor', 'actual', 'art', 'bad', 'beauti', 'believ', 'best', 'better', 'big']
length is : 82


In [ ]:
vectorizer6 = CountVectorizer(token_pattern='[a-z]{3,10}', min_df=10, stop_words='english').fit(docs_clean) # stop_words is used to remove english words
vocab = vectorizer6.get_feature_names()
print(vocab[:10])
print('length is :',len(vocab))

['act', 'actor', 'actual', 'art', 'bad', 'beauti', 'believ', 'best', 'better', 'big']
length is : 81


/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['neverthele'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


* So far we have only extracted valid tokens using get_feature_names()

### Tranforming text doc in to document term matrix

In [ ]:
dtm = vectorizer6.transform(docs_clean)
dtm

<748x81 sparse matrix of type '<class 'numpy.int64'>'
	with 1711 stored elements in Compressed Sparse Row format>

In [ ]:
dtm.toarray() #converting compressed doc into an array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
df_dtm = pd.DataFrame(dtm.toarray()) # large arrays will throw memory error while converting into dataframes if datasets are bigger
df_dtm.shape

(748, 81)

In [ ]:
df_dtm.head()

0   1   2   3   4   5   6   7   8   ...  72  73  74  75  76  77  78  79  80
0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
2   1   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
3   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
4   0   0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   0   0

[5 rows x 81 columns]

In [ ]:
df_dtm = pd.DataFrame(dtm.toarray(), columns=vocab) # Using 'columns=vocab' will give us token names as columns
df_dtm.head()

act  actor  actual  art  bad  beauti  ...  work  wors  worst  worth  write  year
0    0      0       0    0    0       0  ...     0     0      0      0      0     0
1    0      0       0    0    0       0  ...     0     0      0      0      0     0
2    1      0       0    0    0       0  ...     0     0      0      0      0     0
3    0      0       0    0    0       0  ...     0     0      0      0      0     0
4    0      0       0    0    0       0  ...     0     0      0      0      0     0

[5 rows x 81 columns]

**Bigram Vectorizer** - 
* single token - two words
* using CountVectorizer

In [ ]:
bigram_vectorizer = CountVectorizer(token_pattern='[a-z]{3,10}', min_df=2,
                                    stop_words='english',
                                    ngram_range=(2,2)).fit(docs_clean) # ngram_range=(2,2) to specify no of words in individual tokens
bigram_dtm = bigram_vectorizer.transform(docs_clean)
bigram_vocab = bigram_vectorizer.get_feature_names()

df_dtm_bigram = pd.DataFrame(bigram_dtm.toarray(), columns=bigram_vocab)
print(df_dtm_bigram.shape)
df_dtm_bigram.head()

(748, 202)


/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['neverthele'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


accus murder  act bad  act suck  ...  worst seri  worth check  year old
0             0        0         0  ...           0            0         0
1             0        0         0  ...           0            0         0
2             0        0         0  ...           0            0         0
3             0        0         0  ...           0            0         0
4             0        0         0  ...           0            0         0

[5 rows x 202 columns]

**Trigram Vectorizer** - 
* single token - three words
* using CountVectorizer

In [ ]:
trigram_vectorizer = CountVectorizer(token_pattern='[a-z]{3,10}', min_df=2,
                                    stop_words='english',
                                    ngram_range=(3,3)).fit(docs_clean) # ngram_range=(3,3) to specify no of words in individual tokens
trigram_dtm = trigram_vectorizer.transform(docs_clean)
trigram_vocab = trigram_vectorizer.get_feature_names()

df_dtm_trigram = pd.DataFrame(trigram_dtm.toarray(), columns=trigram_vocab)
print(df_dtm_trigram.shape)
df_dtm_trigram.head()

/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['neverthele'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


(748, 9)


best scene movi  definit worth check  ...  seen entir life  wast time watch
0                0                    0  ...                0                0
1                0                    0  ...                0                0
2                0                    0  ...                0                0
3                0                    0  ...                0                0
4                1                    0  ...                0                0

[5 rows x 9 columns]